// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (uploader_id, name, mime_type, size, path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uploader_id, name, mime_type, size, path, created_at
`

type CreateFileParams struct {
	UploaderID uuid.UUID `db:"uploader_id" json:"uploader_id"`
	Name       string    `db:"name" json:"name"`
	MimeType   string    `db:"mime_type" json:"mime_type"`
	Size       int64     `db:"size" json:"size"`
	Path       string    `db:"path" json:"path"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.queryRow(ctx, q.createFileStmt, createFile,
		arg.UploaderID,
		arg.Name,
		arg.MimeType,
		arg.Size,
		arg.Path,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = $1 AND uploader_id = $2
`

type DeleteFileParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	UploaderID uuid.UUID `db:"uploader_id" json:"uploader_id"`
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.exec(ctx, q.deleteFileStmt, deleteFile, arg.ID, arg.UploaderID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, uploader_id, name, mime_type, size, path, created_at FROM files WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.queryRow(ctx, q.getFileByIDStmt, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}
