// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type RefreshToken struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	UserID            uuid.UUID      `db:"user_id" json:"user_id"`
	TokenHash         string         `db:"token_hash" json:"token_hash"`
	ExpiresAt         time.Time      `db:"expires_at" json:"expires_at"`
	RevokedAt         sql.NullTime   `db:"revoked_at" json:"revoked_at"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UserAgent         sql.NullString `db:"user_agent" json:"user_agent"`
	IpAddress         pqtype.Inet    `db:"ip_address" json:"ip_address"`
	ReplacedByTokenID uuid.NullUUID  `db:"replaced_by_token_id" json:"replaced_by_token_id"`
}

type User struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
	Name         sql.NullString `db:"name" json:"name"`
	Email        string         `db:"email" json:"email"`
	PasswordHash string         `db:"password_hash" json:"password_hash"`
}
