// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at, user_agent, ip_address)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at, user_agent, ip_address, replaced_by_token_id
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID      `db:"user_id" json:"user_id"`
	TokenHash string         `db:"token_hash" json:"token_hash"`
	ExpiresAt time.Time      `db:"expires_at" json:"expires_at"`
	UserAgent sql.NullString `db:"user_agent" json:"user_agent"`
	IpAddress pqtype.Inet    `db:"ip_address" json:"ip_address"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.queryRow(ctx, q.createRefreshTokenStmt, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.ReplacedByTokenID,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at, user_agent, ip_address, replaced_by_token_id FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.queryRow(ctx, q.getRefreshTokenByHashStmt, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.ReplacedByTokenID,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = NOW() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.exec(ctx, q.revokeAllUserRefreshTokensStmt, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.revokeRefreshTokenStmt, revokeRefreshToken, id)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW(), replaced_by_token_id = $2 WHERE id = $1
`

type RotateRefreshTokenParams struct {
	ID                uuid.UUID     `db:"id" json:"id"`
	ReplacedByTokenID uuid.NullUUID `db:"replaced_by_token_id" json:"replaced_by_token_id"`
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error {
	_, err := q.exec(ctx, q.rotateRefreshTokenStmt, rotateRefreshToken, arg.ID, arg.ReplacedByTokenID)
	return err
}
